# Generated by Django 5.0.2 on 2024-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='register',
            name='phno',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
