# Generated by Django 5.0.2 on 2024-02-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_register_address_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register1_table',
        ),
    ]
