# Generated by Django 5.0.2 on 2024-02-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register_table',
        ),
    ]
