# Generated by Django 5.0.2 on 2024-02-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phno',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
