# Generated by Django 5.0.2 on 2024-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_register_email_alter_register_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='phno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
